#pragma once

using namespace ATL;

template <class T>
class CProxy_ITwoWayIPCManagerEvents : public IConnectionPointImpl<T, &__uuidof( _ITwoWayIPCManagerEvents ), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
